version: '3'
services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile-prod
    depends_on:
      - db
    command: ./bin/run-prod.sh
    ports:
      - "3030:3030"
  db:
    image: postgres:11
