version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "3030:3030"
    command: /opt/yaindex/bin/run-prod.sh
    environment:
      - PORT=3030
