FROM ruby:2.6.4

ENV RAILS_ON_DOCKER=yes

# Install nodejs 11
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash - && \
  apt-get install -y nodejs

# Install yarn
RUN npm install --global yarn

#Install nginx
RUN apt-get install -y nginx

# cd into /app
ENV APP_PATH=/app

# Install gems
RUN mkdir -p $APP_PATH
COPY Gemfile ${APP_PATH}/Gemfile
COPY Gemfile.lock ${APP_PATH}/Gemfile.lock
WORKDIR ${APP_PATH}
RUN bundle install

COPY package.json ${APP_PATH}/package.json
COPY yarn.lock ${APP_PATH}/yarn.lock
RUN yarn install --check-files

# Configure nginx
RUN useradd -ms /bin/false nginx
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Copy entrypoint
COPY bin/entrypoint.sh /usr/bin
RUN chmod +x /usr/bin/entrypoint.sh

# Copy application files
COPY . ${APP_PATH}

# Build application files
RUN FILES_DIRECTORY="/app/test_files/" bundle exec rake assets:precompile

ENTRYPOINT ["entrypoint.sh"]
EXPOSE 80

CMD ["./bin/run-dev.sh"]
