version: '3'
services:
  rails:
    build: .
    depends_on:
      - db
    command: ./bin/run-dev.sh
    volumes:
      - .:/app:Z
      - /app/node_modules # Fix yarn issues
      - /app/elm-stuff # Fix elm compiler issues
    ports:
      - "3000:3000"
  db:
    image: postgres:12
    volumes:
      - pgdata:/var/lib/postgresql/data
    #ports:
      #- "5432:5432"
volumes:
  pgdata:
