version: '3'
services:
  webpack:
    build: .
    command: /app/bin/run-dev.sh
    volumes:
      - .:/app:Z
      - /app/node_modules # Fix yarn issues
      - /app/elm-stuff # Fix elm compiler issues
    ports:
      - "3030:3030"
