name: Linting

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker images
        run: docker-compose build
      - name: Javascript linting
        run: docker-compose run webpack pnpm run js-lint
      - name: Elm linting
        run: docker-compose run webpack pnpm run elm-lint
