name: Rails Unit Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker images
        run: docker-compose build
      - name: Initialize database
        run: docker-compose run rails bin/initialize.sh
      - name: Run Rails Tests
        run: docker-compose run rails bin/test.sh --ruby
      - name: Run Elm Tests
        run: docker-compose run rails bin/test.sh --elm
